// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sergeylvov.Data;

namespace sergeylvov.Migrations
{
    [DbContext(typeof(LvovContext))]
    [Migration("20210302130424_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("sergeylvov.Data.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 3, 2, 16, 4, 24, 63, DateTimeKind.Local).AddTicks(3888),
                            Text = "<h1>asp.net</h1>",
                            Title = "ASP"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 3, 2, 16, 4, 24, 65, DateTimeKind.Local).AddTicks(9893),
                            Text = "<h1>Entity framework</h1>",
                            Title = "databases"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
